# Generated by Django 4.2.17 on 2025-01-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='diocese',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='small_church',
            name='diocese',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
